const config = window.SITE_CONFIG;
const products = window.PRODUCTS;
const solutions = window.SOLUTIONS;
const main = document.querySelector('#main');
const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const productHref = p => `#/products/${encodeURIComponent(p.id)}`;
const button = (label, href, secondary=false) => `<a class="button ${secondary?'button-secondary':''}" href="${href}">${label}<span aria-hidden="true">↗</span></a>`;
const card = p => `<a class="product-card" href="${productHref(p)}"><span class="product-card-top"><span>${esc(p.category)}</span><span aria-hidden="true">↗</span></span>${p.image?`<span class="product-card-image"><img src="${esc(p.image)}" alt="${esc(p.name)}" loading="lazy" decoding="async"></span>`:`<span class="product-model">${esc(p.id)}</span>`}<strong>${esc(p.name)}</strong><span class="product-summary">${esc(p.summary)}</span><span class="card-more">Explore model <span aria-hidden="true">→</span></span></a>`;
function layout(){
  document.querySelector('#brand').innerHTML = config.logo ? `<img src="${esc(config.logo)}" alt="${esc(config.brand)}">` : `<span class="brand-mark" aria-hidden="true">A</span><strong>${esc(config.brand)}</strong>`;
  document.querySelector('#footer-brand').textContent = config.brand;
  document.title = `${config.brand} | Service Robots`;
}
function home(){return `<section class="hero"><div class="hero-content"><div class="eyebrow">COMMERCIAL SERVICE ROBOTICS <span> / </span> ${esc(config.region)}</div><h1>Robots that make everyday operations move.</h1><p>Explore KEENON cleaning, delivery and service robots with a local partner to help select the right model for your site.</p><div class="hero-actions">${button('Explore robots','#/products')}${button('Discuss your space','#/contact',true)}</div><div class="hero-index"><span>01 / 03</span><span>CLEANING · DELIVERY · SERVICE</span></div></div><div class="hero-art" aria-hidden="true"><div class="hero-grid"></div><div class="hero-word">MOVE<br>BETTER<span>.</span></div><div class="hero-orbit"></div></div></section>
  <section class="section" aria-labelledby="featured"><div class="section-heading"><div><span class="eyebrow">SELECTED MODELS</span><h2 id="featured">Meet the lineup</h2></div><a class="text-link" href="#/products">View all robots ↗</a></div><div class="cards">${products.filter(p=>p.featured).map(card).join('')}</div></section>
  <section class="section dark-band"><span class="eyebrow">BY ENVIRONMENT</span><h2>Designed around the work you do.</h2><div class="solution-list">${solutions.slice(0,4).map((s,i)=>`<a href="#/solutions/${s.id}"><span>0${i+1}</span><strong>${esc(s.name)}</strong><span aria-hidden="true">↗</span></a>`).join('')}</div></section>
  <section class="section closing"><div><span class="eyebrow">START A CONVERSATION</span><h2>Find the right robot for your operation.</h2></div>${button('Contact us','#/contact')}</section>`}
function catalog(){let categories=['All',...new Set(products.map(p=>p.category))];return `<section class="page-intro"><span class="eyebrow">PRODUCT CATALOG</span><h1>Explore the robots.</h1><p>Browse the manufacturer's current categories. Ask us about local availability, demonstrations and deployment.</p></section><section class="section catalog"><div class="filters" role="group" aria-label="Filter by category">${categories.map(c=>`<button type="button" data-category="${esc(c)}" aria-pressed="${c==='All'}">${esc(c)}</button>`).join('')}</div><p class="count" aria-live="polite">${products.length} models</p><div class="cards" id="product-grid">${products.map(card).join('')}</div></section>`}

function c40Details(){
  const m='https://storage.keenon.cn/uploads/';
  const media=(path,alt)=>`<img src="${m+path}" alt="${esc(alt)}" loading="lazy" decoding="async">`;
  const specs=[
    ['Dimensions without squeegee','578 × 500 × 690 mm','22.76 × 19.69 × 27.17 in'],
    ['Dimensions with squeegee','616 × 550 × 690 mm','24.25 × 21.65 × 27.17 in'],
    ['Sweeping width','560 mm with dual side brushes','22.05 in'],
    ['Vacuuming and scrubbing width','400 mm','15.75 in'],
    ['Clean / waste water tanks','16 L / 11 L','4.23 / 2.91 US gal'],
    ['Maximum runtime','Up to 5 h scrubbing; up to 12 h sweeping',''],
    ['Battery','DC 25.6 V, 50 Ah',''],
    ['Weight with battery','70 kg','154.3 lb'],
    ['Minimum passage width','650 mm','25.59 in'],
    ['Charging time','2 h; quick battery replacement supported',''],
    ['Cleaning efficiency','Up to 1,100 m²/h','Up to 11,840 ft²/h'],
    ['Dust bag','8 L','Manufacturer estimates 4–8 days of dust']
  ];
  const accessories=['Sweeping brush','Scrubbing brush','Squeegee blade','Side brush','HEPA filter','Sweeping fiber brush','Dust mopping brush','Dust bag'];
  return `<section class="section c40-intro"><span class="eyebrow">KLEENBOT C40 / PRODUCT OVERVIEW</span><h2>Four cleaning modes. One compact robot.</h2><p>The C40 sweeps, vacuums, scrubs and dust pushes. Its triple-brush arrangement separates dry debris from wet cleaning, supporting routine care across mixed floor surfaces.</p><div class="c40-highlights"><div><strong>4 in 1</strong><span>Cleaning functions</span></div><div><strong>400 mm</strong><span>Vacuum and scrub width</span></div><div><strong>1,100 m²/h</strong><span>Maximum rated cleaning efficiency</span></div><div><strong>650 mm</strong><span>Minimum passage width</span></div></div></section>
  <section class="section c40-split"><div>${media('20260723/374f60b7fb3b90e5bd457c575b836cc6.jpg','KLEENBOT C40 product showcase')}</div><div><span class="eyebrow">CLEANING SYSTEM</span><h2>Built for dry and wet messes.</h2><p>Two front rollers collect dry debris before the rear roller scrubs the floor. The separation helps keep the dust compartment dry while the suction system recovers wastewater.</p><ul><li>Handles hair, paper scraps and dust as well as everyday liquid spills.</li><li>Manufacturer states floors can dry in around 30 seconds after scrubbing under suitable conditions.</li><li>Designed for short-pile carpet and common hard floors including tile, vinyl, wood, marble, epoxy, granite and artificial stone. Match the mode to the surface.</li></ul></div></section>
  <section class="section c40-section"><span class="eyebrow">OPERATION AND CONTROL</span><h2>Manage cleaning around your schedule.</h2><div class="c40-feature-grid"><article><h3>Digital management</h3><p>Use the manufacturer’s app or web tools for tasks, status, remote dispatch and cleaning reports.</p></article><article><h3>Navigation and detection</h3><p>VSLAM route planning works with LiDAR, stereo vision, line lasers and ultrasonic sensors to detect obstacles.</p></article><article><h3>Mixed floor workflows</h3><p>Automatic carpet and hard-floor recognition, pause-and-resume scanning and multi-robot scheduling support varied sites.</p></article><article><h3>Building integration</h3><p>The official product page lists IoT-enabled elevator and door passage. Confirm compatibility and installation needs for each building.</p></article></div></section>
  <section class="section c40-split c40-split-reverse"><div>${media('20260924/acbfbdb5def648e39eecbcf3eed27520.jpg','C40 cleaning feature illustration')}</div><div><span class="eyebrow">MAINTENANCE</span><h2>Designed for quick daily care.</h2><p>Modular components, a removable washable dirty-water tank and a replaceable battery simplify routine upkeep. KEENON states a five-second battery swap and about 35 seconds for daily care.</p><p>With compatible equipment, the robot can return to charge and automate fresh-water filling, wastewater drainage and detergent dosing. Ask us which station and site connections are required.</p></div></section>
  <section class="section c40-gallery"><div class="section-heading"><div><span class="eyebrow">PRODUCT IMAGES</span><h2>See the C40 in detail.</h2></div></div><div class="c40-gallery-grid">${media('20260924/fbd22c652d794a2d8de4cf3069d2cb8e.jpg','C40 feature view')}${media('20260804/572f8ab6f027921676f84d06c9e10e3b.png','C40 cleaning system illustration')}${media('20260723/c0e708a8f1f458a625affaca55682fa9.jpg','C40 in an application setting')}</div></section>
  <section class="section c40-specs"><span class="eyebrow">TECHNICAL DATA</span><h2>Product specifications.</h2><div class="c40-spec-list">${specs.map(([name,metric,imperial])=>`<div><dt>${esc(name)}</dt><dd>${esc(metric)}${imperial?`<small>${esc(imperial)}</small>`:''}</dd></div>`).join('')}</div><p class="c40-note">Figures are manufacturer-published ratings. Actual results depend on conditions, configuration and usage.</p></section>
  <section class="section c40-accessories"><span class="eyebrow">CONSUMABLES AND PARTS</span><h2>Available accessories.</h2><ul>${accessories.map(x=>`<li>${esc(x)}</li>`).join('')}</ul><p>Confirm accessory availability and compatibility before ordering.</p></section>
  <section class="section c40-cta"><div><span class="eyebrow">PLAN YOUR DEPLOYMENT</span><h2>Is C40 a fit for your space?</h2><p>Tell us about your floors, square footage, cleaning schedule and water access. We can discuss the robot and any required station or building integration.</p></div>${button('Ask about C40','#/contact?model=C40')}</section>
  <div class="c40-source">Images and product information: <a href="https://www.keenon.com/en/product/C40" target="_blank" rel="noopener">KEENON Robotics C40 official product page ↗</a></div>`;
}
function detail(p){return `<div class="breadcrumbs"><a href="#/products">Robots</a><span>/</span><span>${esc(p.category)}</span><span>/</span><span>${esc(p.id)}</span></div><section class="detail-hero"><div><span class="eyebrow">${esc(p.category)} / ${esc(config.manufacturer)}</span><h1>${esc(p.name)}</h1><p>${esc(p.summary)}</p><div class="hero-actions">${button('Ask about this model',`#/contact?model=${encodeURIComponent(p.id)}`)}${button('Manufacturer details',esc(p.source),true)}</div></div><div class="detail-graphic">${p.image?`<img src="${esc(p.image)}" alt="${esc(p.name)}" decoding="async">`:`<span>${esc(p.id)}</span>`}<small>KEENON MODEL</small></div></section>${p.video?`<section class="section product-video-section" aria-label="${esc(p.name)} video"><div class="section-heading"><div><span class="eyebrow">IN ACTION</span><h2>See ${esc(p.name)} at work.</h2></div><a class="text-link" href="${esc(p.source)}" target="_blank" rel="noopener">Video by KEENON ↗</a></div><video controls playsinline preload="none" poster="${esc(p.image||"")}" aria-label="${esc(p.name)} product video"><source src="${esc(p.video)}" type="video/mp4">Your browser does not support video playback.</video></section>`:""}${p.id==="C40"?c40Details():`<section class="section detail-bottom"><div><span class="eyebrow">OVERVIEW</span><h2>Plan a deployment that fits.</h2><p>We can discuss operating hours, floor layout, integration needs, local service and availability for ${esc(p.name)}. Product specifications are subject to manufacturer confirmation.</p></div>${p.features?`<div class="details-panel"><h3>Highlights</h3><ul>${p.features.map(f=>`<li>${esc(f)}</li>`).join('')}</ul>${p.specs?`<h3>Selected manufacturer specifications</h3><dl>${p.specs.map(([k,v])=>`<div><dt>${esc(k)}</dt><dd>${esc(v)}</dd></div>`).join('')}</dl>`:''}</div>`:`<div class="details-panel"><h3>Manufacturer resources</h3><p>Detailed features and technical specifications are available on KEENON's product page.</p><a class="text-link" href="${esc(p.source)}" target="_blank" rel="noopener">View official product page ↗</a></div>`}</section>`}<section class="section"><div class="section-heading"><h2>Other models</h2><a class="text-link" href="#/products">Full catalog ↗</a></div><div class="cards">${products.filter(x=>x.category===p.category&&x.id!==p.id).slice(0,3).map(card).join('')}</div></section>`}
function solutionIndex(){return `<section class="page-intro"><span class="eyebrow">SOLUTIONS</span><h1>Built for your environment.</h1><p>Start with the workflows that matter in your space, then select the robot and service plan to match.</p></section><section class="section solution-cards">${solutions.map((s,i)=>`<a href="#/solutions/${s.id}" class="solution-card"><span>0${i+1} / ${esc(s.name.toUpperCase())}</span><h2>${esc(s.name)}</h2><p>${esc(s.description)}</p><small>Explore use case ↗</small></a>`).join('')}</section>`}
function solutionDetail(s){return `<div class="breadcrumbs"><a href="#/solutions">Solutions</a><span>/</span><span>${esc(s.name)}</span></div><section class="page-intro"><span class="eyebrow">INDUSTRY SOLUTION</span><h1>${esc(s.name)}</h1><p>${esc(s.description)}</p><div class="hero-actions">${button('Talk through your needs','#/contact')}${button('Browse robots','#/products',true)}</div></section><section class="section"><span class="eyebrow">POSSIBLE MODELS</span><h2>Explore a starting point.</h2><p>Common models to discuss: ${esc(s.models)}. Final selection depends on your environment and requirements.</p><div class="cards">${products.filter(p=>s.models.split(' · ').includes(p.id)).map(card).join('')}</div></section>`}
function contact(){let model=new URLSearchParams((location.hash.split('?')[1]||'')).get('model');let email=config.email.trim(),phone=config.phone.trim();return `<section class="page-intro"><span class="eyebrow">LET'S TALK</span><h1>Tell us what you need.</h1><p>Share your space, workflow and preferred timeline. We can help compare models and plan a demonstration.</p></section><section class="section contact-grid"><div><h2>Sales inquiries</h2><p>${model?`Interested in <strong>${esc(model)}</strong>? `:''}Connect with ${esc(config.brand)} about your project.</p><dl class="contact-data">${email?`<div><dt>Email</dt><dd><a href="mailto:${encodeURIComponent(email)}?subject=${encodeURIComponent((model||'Robot')+' inquiry')}">${esc(email)}</a></dd></div>`:''}${phone?`<div><dt>Phone</dt><dd><a href="tel:${esc(phone.replace(/[^+\d]/g,''))}">${esc(phone)}</a></dd></div>`:''}${config.address?`<div><dt>Address</dt><dd>${esc(config.address)}</dd></div>`:''}<div><dt>Region</dt><dd>${esc(config.region)}</dd></div></dl>${!email&&!phone?'<p class="setup-note">Contact details are being added. Please check back soon.</p>':''}</div><div class="contact-panel"><span class="eyebrow">FOR A USEFUL FIRST CALL</span><h3>What to prepare</h3><ul><li>Your building or floor area</li><li>Cleaning or delivery workflow</li><li>Working hours and access needs</li><li>Site location and ideal start date</li></ul></div></section>`}
function route(){const raw=decodeURIComponent(location.hash.slice(2).split('?')[0]||'');const parts=raw.split('/').filter(Boolean);let html;if(parts[0]==='products'&&parts[1]){const p=products.find(x=>x.id.toLowerCase()===parts[1].toLowerCase());html=p?detail(p):notFound()}else if(parts[0]==='products')html=catalog();else if(parts[0]==='solutions'&&parts[1]){const s=solutions.find(x=>x.id===parts[1]);html=s?solutionDetail(s):notFound()}else if(parts[0]==='solutions')html=solutionIndex();else if(parts[0]==='contact')html=contact();else if(!parts.length)html=home();else html=notFound();main.innerHTML=html;document.title=`${parts.length?parts[0][0].toUpperCase()+parts[0].slice(1)+' | ':''}${config.brand}`;document.querySelectorAll('.filters button').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.filters button').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));let selected=b.dataset.category;let visible=products.filter(p=>selected==='All'||p.category===selected);document.querySelector('#product-grid').innerHTML=visible.map(card).join('');document.querySelector('.count').textContent=`${visible.length} models`}));window.scrollTo({top:0,behavior:'instant'})}
function notFound(){return `<section class="page-intro"><h1>Page not found.</h1>${button('Return home','#/')}</section>`}
layout();addEventListener('hashchange',route);route();
